# Generated by Django 3.0.6 on 2020-05-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('xp', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UnsavedLearnword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=50, verbose_name='german word')),
                ('russian_word', models.CharField(max_length=50, verbose_name='russian word')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.User')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=50, verbose_name='german word')),
                ('russian_word', models.CharField(max_length=50, verbose_name='russian word')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('learnword_id', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.User')),
            ],
        ),
        migrations.CreateModel(
            name='Learnword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_word', models.CharField(max_length=50, verbose_name='german word')),
                ('russian_word', models.CharField(max_length=50, verbose_name='russian word')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('german_pronunciation', models.FileField(blank=True, null=True, upload_to='Audio/de/')),
                ('russian_pronunciation', models.FileField(blank=True, null=True, upload_to='Audio/ru/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.User')),
            ],
        ),
    ]
