# Generated by Django 3.0.6 on 2020-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='german_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='Audio/de/'),
        ),
        migrations.AddField(
            model_name='training',
            name='russian_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='Audio/ru/'),
        ),
    ]
